//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerWishlist
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string ProductId { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
