//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TMATS00012020Entities : DbContext
    {
        public TMATS00012020Entities()
            : base("name=TMATS00012020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GRP_MASTER> GRP_MASTER { get; set; }
        public virtual DbSet<ITMMAST> ITMMASTs { get; set; }
        public virtual DbSet<itmmast_photos> itmmast_photos { get; set; }
        public virtual DbSet<CustomerCart> CustomerCarts { get; set; }
        public virtual DbSet<CustomerWishlist> CustomerWishlists { get; set; }
        public virtual DbSet<CustomerRegistration> CustomerRegistrations { get; set; }
    }
}
