//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRP_MASTER
    {
        public string GRP_CD { get; set; }
        public string GRP_SNAME { get; set; }
        public string GRP_NAME { get; set; }
        public string GROUP_YN { get; set; }
        public string FOR_GRP_CD { get; set; }
        public string LEVEL_TEXT { get; set; }
        public int Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<double> Customer_Profit_Percentage { get; set; }
        public Nullable<double> Delear_Profit_Percentage { get; set; }
        public string Export_To_Zen_Cart { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Notes { get; set; }
        public string GRP_sname_SL { get; set; }
    }
}
