//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class itmmast_photos
    {
        public int Record_id { get; set; }
        public string item_cd { get; set; }
        public Nullable<int> Item_Pic_cd { get; set; }
        public string image_name { get; set; }
        public byte[] image_data { get; set; }
    }
}
