//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITMMAST
    {
        public string ITEM_CD { get; set; }
        public string ITEM_DESC { get; set; }
        public string GRP_CD { get; set; }
        public string UNIT { get; set; }
        public Nullable<double> RATE { get; set; }
        public Nullable<int> Packing_Qty { get; set; }
        public Nullable<double> SALE_PRICE { get; set; }
        public Nullable<double> AVG_COST { get; set; }
        public Nullable<double> USER_AVG_COST { get; set; }
        public Nullable<double> OP_STK { get; set; }
        public Nullable<double> OP_RATE { get; set; }
        public Nullable<double> OP_VAL { get; set; }
        public Nullable<int> MIN_STK_LEVEL { get; set; }
        public Nullable<int> MAX_STK_LEVEL { get; set; }
        public Nullable<int> REORDER_LEVEL { get; set; }
        public string ABC { get; set; }
        public string XYZ { get; set; }
        public Nullable<double> GI_QTY_MM { get; set; }
        public Nullable<double> GI_VAL_MM { get; set; }
        public Nullable<double> IS_QTY_MM { get; set; }
        public Nullable<double> IS_VAL_MM { get; set; }
        public Nullable<double> CL_STK { get; set; }
        public Nullable<double> CL_VAL { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> OP_DATE { get; set; }
        public string USER_NAME { get; set; }
        public string Active_InActive { get; set; }
        public string Inv_NonInv { get; set; }
        public string Subtitution { get; set; }
        public string Model_No { get; set; }
        public Nullable<double> CostADdPer { get; set; }
        public Nullable<double> unit_dec_After_Conv { get; set; }
        public Nullable<double> Temp_GI_QTY_MM { get; set; }
        public Nullable<double> TEMP_IS_QTY_MM { get; set; }
        public Nullable<double> TEMP_CL_QTY_MM { get; set; }
        public Nullable<double> TEMP_AVG_COST { get; set; }
        public string Super_session_to { get; set; }
        public string Brand_Name { get; set; }
        public string Made_in { get; set; }
        public string Vehical_Name { get; set; }
        public string Material { get; set; }
        public string Size { get; set; }
        public string Type_Of_Item { get; set; }
        public string Alias_01 { get; set; }
        public string Alias_02 { get; set; }
        public Nullable<double> Last_Cost { get; set; }
        public Nullable<System.DateTime> Last_Cost_Date { get; set; }
        public Nullable<double> Per_Add_at_Cost_For_Display { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string User_Avg_Cost_Taken_In_Inv_Value_Y_N { get; set; }
        public string Packing_Unit { get; set; }
        public string Collection_code { get; set; }
        public Nullable<double> Last_Purchase_Qty { get; set; }
        public Nullable<double> SALE_PRICE2 { get; set; }
        public Nullable<double> SALE_PRICE3 { get; set; }
        public string Bar_Code { get; set; }
        public string Batch_Req_Y_N { get; set; }
        public string Remark_Memo_Itmmast { get; set; }
        public string Updated_Y_N { get; set; }
        public Nullable<System.DateTime> Updated_Date_Time { get; set; }
        public Nullable<double> Expiry_Days { get; set; }
        public string Rate_Change_Allow { get; set; }
        public string Trasnfer_To_POS_Location { get; set; }
        public string Restaurant_Stock_Calc_To_Item_Cd { get; set; }
        public Nullable<double> Restaurant_Item_Cd_Conv { get; set; }
        public string Restaurant_Change_Rate_Allowed { get; set; }
        public string Type_Of_Item_F_B_T_G { get; set; }
        public Nullable<int> C_001 { get; set; }
        public Nullable<int> C_002 { get; set; }
        public Nullable<int> C_003 { get; set; }
        public Nullable<int> C_004 { get; set; }
        public Nullable<int> C_005 { get; set; }
        public Nullable<int> C_006 { get; set; }
        public Nullable<int> C_007 { get; set; }
        public Nullable<int> C_008 { get; set; }
        public Nullable<int> C_009 { get; set; }
        public Nullable<int> C_010 { get; set; }
        public Nullable<int> C_011 { get; set; }
        public Nullable<int> C_012 { get; set; }
        public Nullable<int> C_013 { get; set; }
        public Nullable<int> C_014 { get; set; }
        public Nullable<int> C_015 { get; set; }
        public string Export_To_Zen_Cart { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public int Item_id { get; set; }
        public Nullable<double> tax01 { get; set; }
        public Nullable<double> tax02 { get; set; }
        public Nullable<double> POS_Disc_Per { get; set; }
        public Nullable<System.DateTime> POS_Disc_Dt_From { get; set; }
        public Nullable<System.DateTime> POS_Disc_Dt_To { get; set; }
        public string Alias_03 { get; set; }
        public string Alias_04 { get; set; }
        public string Alias_05 { get; set; }
        public string Alias_06 { get; set; }
        public string Alias_07 { get; set; }
        public string Alias_08 { get; set; }
        public string Alias_09 { get; set; }
        public string Alias_10 { get; set; }
        public Nullable<System.DateTime> Last_Current_PUR_Date { get; set; }
        public Nullable<System.DateTime> Last_Current_SALE_Date { get; set; }
        public Nullable<System.DateTime> Last_avg_cost_calc_date { get; set; }
        public Nullable<System.DateTime> last_import_cost_date { get; set; }
        public Nullable<double> last_import_cost { get; set; }
        public Nullable<double> last_import_Qty { get; set; }
        public string SP_Inclusive_TAX { get; set; }
        public string Allow_Item_Name_Modification { get; set; }
        public Nullable<int> Loyalty_Points { get; set; }
        public Nullable<double> tax03 { get; set; }
        public Nullable<double> tax04 { get; set; }
        public Nullable<double> tax05 { get; set; }
        public Nullable<double> tax06 { get; set; }
        public Nullable<double> tax07 { get; set; }
        public Nullable<double> tax08 { get; set; }
        public string ITEM_DESC_SL { get; set; }
        public Nullable<double> SALE_PRICE4 { get; set; }
        public Nullable<double> SALE_PRICE5 { get; set; }
        public Nullable<decimal> Item_Weight { get; set; }
        public Nullable<decimal> Item_Volume { get; set; }
        public Nullable<int> NO_OF_MONTH_ST_REQ { get; set; }
        public Nullable<int> LEAD_TIME_IN_MONTH { get; set; }
    }
}
